name = "SDFResults"
uuid = "3e51950c-1d7d-41c0-8bda-2201d9a6ffd5"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com> and contributors"]
version = "0.1.1"

[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
EPOCHInput = "691e61f8-6502-44a1-a143-5276a0aa0dc4"
PICDataStructures = "cb18667b-f199-4b8b-b886-9916fef47a26"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
SDFReader = "bd0b56a1-724b-4db5-9cfb-6781c02e0e49"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
EPOCHInput = "0.1"
PICDataStructures = "0.1"
SDFReader = "0.3"
StatsBase = "0.33"
Transducers = "0.4"
PhysicalConstants = "0.2"
ThreadsX = "0.1"
BangBang = "0.3"
Unitful = "1.0"
julia = "1.5"

[extras]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Serialization"]
